# Generated by Django 5.1.3 on 2024-11-25 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.TimeField(blank=True, default=datetime.datetime(2024, 11, 25, 15, 36), null=True),
        ),
    ]
