# Generated by Django 5.1.6 on 2025-04-27 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.TimeField(blank=True, default=datetime.datetime(2025, 4, 28, 1, 49), null=True),
        ),
    ]
